server:
  port: 9000

api:
  url: http://${ENV:prod}-rates:9999/exchangeRates

# https://github.com/camunda-community-hub/spring-zeebe#configuring-camunda-platform-8-saas-connection
# https://github.com/camunda-community-hub/spring-zeebe#additional-configuration-options

zeebe:
  client:
    broker:
      gateway-address: localhost:26500
    security:
      plaintext: true
    cloud:
      client-id: zeebe
      client-secret: zecret
      auth-url: http://localhost:18080/auth/realms/camunda-platform/protocol/openid-connect/token

tasklist:
  url: http://localhost:8082
  keycloak-url: http://localhost:18080
  client-id: ${zeebe.client.cloud.client-id}
  client-secret: ${zeebe.client.cloud.client-secret}

camunda:
  connector:
    polling:
      enabled: false
    webhook:
      enabled: false
