zeebe:
  client:
    cloud:
      region: ont-1
      cluster-id: 35eedd8b-35e5-4373-8a4c-f211043e42da
      client-id: kMVnghsS4TV7lqocluB9AsLNNRSNsCr1
      client-secret: EIt0BqN-bEK~hVbvN8tZO4vPgmZYQ-RbQdnqRwIsyQnZ9Bp-h5XJBT9NuS8cFnu-

tasklist:
  url: https://ont-1.tasklist.camunda.io/35eedd8b-35e5-4373-8a4c-f211043e42da
  keycloak-url: https://login.cloud.camunda.io/oauth/token
  client-id: ${zeebe.client.cloud.client-id}
  client-secret: ${zeebe.client.cloud.client-secret}
