zeebe:
  client:
    cloud:
      region: ont-1
      clusterId: 35eedd8b-35e5-4373-8a4c-f211043e42da
      clientId: kMVnghsS4TV7lqocluB9AsLNNRSNsCr1
      clientSecret: EIt0BqN-bEK~hVbvN8tZO4vPgmZYQ-RbQdnqRwIsyQnZ9Bp-h5XJBT9NuS8cFnu-
