zeebe:
  client:
    broker:
      gateway-address: localhost:26500
    security:
      plaintext: true
    cloud:
      client-id: zeebe
      client-secret: zecret
      auth-url: http://localhost:18080/auth/realms/camunda-platform/protocol/openid-connect/token