# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21

      - name: Check Dependencies
        run: mvn -B dependency:analyze versions:display-dependency-updates --file pom.xml

      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build
        run: mvn -B package --file pom.xml